server:
  port: 8080


spring:
    datasource:
        name: mysql_test
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.cj.jdbc.Driver
          #基本属性
          url: jdbc:mysql://localhost:3306/alumni information system?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL = false
          username: root
          password: xxa99038329HD
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 200
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 2000

    multipartResover:
      type: org.springframework.web.multipart.commons.CommonsMultipartResolver



#时间问题
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
    mvc:
      static-path-pattern: /image/**
      view:
        prefix:
          classpath: /templates/
    resources:
      static-locations: file:D://software/advert/
    devtools:
      restart:
        enabled: true  #设置开启热部署
    mail:
      host: smtp.163.com
      username: chzs_lz@163.com
      password: xxa99038329
      default-encoding: utf-8
      properties:
        mail:
          smtp:
            auth: true
            starttles:
              enable: true
              required: true
#    热部署工作
    thymeleaf:
      cache: false  #页面不加载缓存，修改即时生效
      mode: LEGACYHTML5     #代表不进行严格检验

mail:
  fromMail:
    addr: chzs_lz@163.com
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.winterchen.model



#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check



sdk:
  alipay:
    dev: true
    sign-type: RSA2
    app-id: 2016092800613430
    private-key:  MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCIn2p4xdmyUlswCdQqT11kpGPCwWAZjaFTF8ZEWCbZg5i6LfWUg+zWhA0Ul4ME/lROml7VM2PISMkkAvC75uKhmFYorDEKdcYcXDAQggvFpwsahIILcsL3hENNnTu3FTm969OHYiM/kROPhI959NT7Qf2ewXehxtJnyYj0XRGKC3aI8UqwHoJkErvBuOFDJsWMV3XVnqgO2RuMn1PitvwII84C8OAYL9spsXBKjeW2SVqW0RfGA5vrIOK6zCpw16gfoC6wzm7X10h5qs58wSqQWswzu1hPyCNnFU1DlR+wpnYoVTFyuPUlZg64sJM/xmDIO5e1AmB8jNplIwiz/2U9AgMBAAECggEAWMxkg4L077YflqWMxMM4zIUcYiUVtQYc6Mj3EMzK0215AumESLdGZFcHuW6QtdooKb6kDKaOIEtOkJ1oonh6rNU6is0AQvAxh5VTmCcuR5U+3klpzM8WcZIBvJyJh4HAOfThU4kxp8s/j3R1XKsJExXdJiZQ/1EeyF5xKYKkN7gtUYWeyOR5qJAmRDWvLbITABx+X+HFjY5OL+YX9v5pEmQ7e0OjGpxEqTlIWeiALOB9KS9hlYILso8Y8SENysxvcRZLw+F2bWYPtZgC8s6hMzc0v31MS8tWtwI8wzenNgjVmqQ10/DA/1LQNatJBhFUvaCfhnHwv2wXHF0NcafTcQKBgQDb4z4lbxVYrNcVvdgIh7PdRk4xchQxDCIG7ncbecKw4+8wxs4OJXodwOK9iYxHTVvZaPCeqcL/MxWUi+l6riTCJ2iaYRR/NYDqISiSqWjbTF6ayyVTTuKgJmnRop3luT0KoQ7YAQ1p+e4nEWqMi1uGwiKMEeL1k63iI/7XWkvPjwKBgQCfD3USp/qOMiloyJiuyVYaeshYPlOMoF5+z/1uKA549N0AeWs2u8hgB6B10V9QP4b2aUzNzBsaUsWLe7qSEn9kPdmaQp4DEK1cqj7rQE7WgKKYyZ9ZKQuToje7irn1WL+tVBtvfNVFZ+Gu0gT1UNq3UQu4cOUNxW5mbRv11ehYcwKBgB8yRFTnR64HB5TsFERRjHEuUlWti7PRttoo5vkc80RJclwHOKDFLGggP4sIgsBy9z8HJmw8RZATXVJv7zYaktiA4tRURaYunxWYkrsMEfZbBWkMvUTugjSafpThb2lyOHjTlNmMfKy2atVcITPDab7auDALMZoJ07erx7Ih+3N9AoGAcFjopj7DuMAxg3N8dKh9CsMC02Fifgef9w5NwQrF/iVmHDmmwsgsJbf9XHqAShw05cNGnm22Dwe7xGOmShqKpHETS+QV27Bh4vvU6TFI/jVpo2V2CfH13VdM6kh4RJVk/bZUkpCnyxguzd5F5kgv1B+ImcQT5YA4FFyozSFDtYUCgYEAz8a7K5lovJCKvDJ8rfPrhjCCXg1ahuigNg0jgKRKNxHY4kEcqO+lVQTXMAFxQY07ADzu2TT6tlcahJ9a4KGltupQbC8Y3ZSH+Q9Z9ZnvgcZg6MI6Yongrq0BG3Zm8lONdejr6vXi+O7Opk65Bmtb2PMTi9hu5XlExtDy+Rx4iLQ=
    alipay-public-key:  MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5vwbN7PZMo/Sa3qvenRCDIlZo5hlWINSnbF96oYa0EzxgDQYGsbzYzWFMwhfjT0fGLaR/dLEtZJEHsBw8AoEczoEtWmu1LNzxBQA8EAQkAivrsnSfiMXDJQE3JoME6KBuHpklHwSE/WrBGx+fvPxx3IUouCYrD7huwIeqzwkeDmq56u6Y/HoHnP/Q/+k5nct5RtrGjIX36Pd55tljRgdOIrTb2GtEXgt/Jho3GV6SU4Zuex2ned4GpuVPgFYa9vmm3JcrUSkIT8bWA8c0kbLMS/HcvgScooWeqEOVDepbgLKTr2lc/h6gwnL+TezwY2EIMbjxbc+ie6BdlF5hk73DQIDAQAB

pay:
  alipay:
    gatewayUrl: https://openapi.alipaydev.com/gateway.do
    appid: 2016092800613430
    appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCIn2p4xdmyUlswCdQqT11kpGPCwWAZjaFTF8ZEWCbZg5i6LfWUg+zWhA0Ul4ME/lROml7VM2PISMkkAvC75uKhmFYorDEKdcYcXDAQggvFpwsahIILcsL3hENNnTu3FTm969OHYiM/kROPhI959NT7Qf2ewXehxtJnyYj0XRGKC3aI8UqwHoJkErvBuOFDJsWMV3XVnqgO2RuMn1PitvwII84C8OAYL9spsXBKjeW2SVqW0RfGA5vrIOK6zCpw16gfoC6wzm7X10h5qs58wSqQWswzu1hPyCNnFU1DlR+wpnYoVTFyuPUlZg64sJM/xmDIO5e1AmB8jNplIwiz/2U9AgMBAAECggEAWMxkg4L077YflqWMxMM4zIUcYiUVtQYc6Mj3EMzK0215AumESLdGZFcHuW6QtdooKb6kDKaOIEtOkJ1oonh6rNU6is0AQvAxh5VTmCcuR5U+3klpzM8WcZIBvJyJh4HAOfThU4kxp8s/j3R1XKsJExXdJiZQ/1EeyF5xKYKkN7gtUYWeyOR5qJAmRDWvLbITABx+X+HFjY5OL+YX9v5pEmQ7e0OjGpxEqTlIWeiALOB9KS9hlYILso8Y8SENysxvcRZLw+F2bWYPtZgC8s6hMzc0v31MS8tWtwI8wzenNgjVmqQ10/DA/1LQNatJBhFUvaCfhnHwv2wXHF0NcafTcQKBgQDb4z4lbxVYrNcVvdgIh7PdRk4xchQxDCIG7ncbecKw4+8wxs4OJXodwOK9iYxHTVvZaPCeqcL/MxWUi+l6riTCJ2iaYRR/NYDqISiSqWjbTF6ayyVTTuKgJmnRop3luT0KoQ7YAQ1p+e4nEWqMi1uGwiKMEeL1k63iI/7XWkvPjwKBgQCfD3USp/qOMiloyJiuyVYaeshYPlOMoF5+z/1uKA549N0AeWs2u8hgB6B10V9QP4b2aUzNzBsaUsWLe7qSEn9kPdmaQp4DEK1cqj7rQE7WgKKYyZ9ZKQuToje7irn1WL+tVBtvfNVFZ+Gu0gT1UNq3UQu4cOUNxW5mbRv11ehYcwKBgB8yRFTnR64HB5TsFERRjHEuUlWti7PRttoo5vkc80RJclwHOKDFLGggP4sIgsBy9z8HJmw8RZATXVJv7zYaktiA4tRURaYunxWYkrsMEfZbBWkMvUTugjSafpThb2lyOHjTlNmMfKy2atVcITPDab7auDALMZoJ07erx7Ih+3N9AoGAcFjopj7DuMAxg3N8dKh9CsMC02Fifgef9w5NwQrF/iVmHDmmwsgsJbf9XHqAShw05cNGnm22Dwe7xGOmShqKpHETS+QV27Bh4vvU6TFI/jVpo2V2CfH13VdM6kh4RJVk/bZUkpCnyxguzd5F5kgv1B+ImcQT5YA4FFyozSFDtYUCgYEAz8a7K5lovJCKvDJ8rfPrhjCCXg1ahuigNg0jgKRKNxHY4kEcqO+lVQTXMAFxQY07ADzu2TT6tlcahJ9a4KGltupQbC8Y3ZSH+Q9Z9ZnvgcZg6MI6Yongrq0BG3Zm8lONdejr6vXi+O7Opk65Bmtb2PMTi9hu5XlExtDy+Rx4iLQ=
    alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5vwbN7PZMo/Sa3qvenRCDIlZo5hlWINSnbF96oYa0EzxgDQYGsbzYzWFMwhfjT0fGLaR/dLEtZJEHsBw8AoEczoEtWmu1LNzxBQA8EAQkAivrsnSfiMXDJQE3JoME6KBuHpklHwSE/WrBGx+fvPxx3IUouCYrD7huwIeqzwkeDmq56u6Y/HoHnP/Q/+k5nct5RtrGjIX36Pd55tljRgdOIrTb2GtEXgt/Jho3GV6SU4Zuex2ned4GpuVPgFYa9vmm3JcrUSkIT8bWA8c0kbLMS/HcvgScooWeqEOVDepbgLKTr2lc/h6gwnL+TezwY2EIMbjxbc+ie6BdlF5hk73DQIDAQAB
    returnUrl: http://yxep7y.natappfree.cc/alipay/return
    notifyUrl: http://yxep7y.natappfree.cc/alipay/notify

debug: true

